import type {
  PoliticalParty,
  ElectionCycle,
  ElectionContest,
} from "@/types";

export const INEC_2027_POLITICAL_PARTIES: PoliticalParty[] = [
  {
    id: "apc",
    acronym: "APC",
    name: "All Progressives Congress",
    inec_registered: true,
    status: "active",
    color: "#1B4F72",
  },
  {
    id: "pdp",
    acronym: "PDP",
    name: "Peoples Democratic Party",
    inec_registered: true,
    status: "active",
    color: "#27AE60",
  },
  {
    id: "lp",
    acronym: "LP",
    name: "Labour Party",
    inec_registered: true,
    status: "active",
    color: "#D35400",
  },
  {
    id: "apga",
    acronym: "APGA",
    name: "All Progressives Grand Alliance",
    inec_registered: true,
    status: "active",
    color: "#8E44AD",
  },
  {
    id: "nnpp",
    acronym: "NNPP",
    name: "New Nigeria Peoples Party",
    inec_registered: true,
    status: "active",
    color: "#C0392B",
  },
  {
    id: "adc",
    acronym: "ADC",
    name: "African Democratic Congress",
    inec_registered: true,
    status: "active",
    color: "#F39C12",
  },
  {
    id: "sdp",
    acronym: "SDP",
    name: "Social Democratic Party",
    inec_registered: true,
    status: "active",
    color: "#16A085",
  },
  {
    id: "ypp",
    acronym: "YPP",
    name: "Young Progressives Party",
    inec_registered: true,
    status: "active",
    color: "#2980B9",
  },
  {
    id: "aa",
    acronym: "AA",
    name: "Action Alliance",
    inec_registered: true,
    status: "active",
    color: "#7F8C8D",
  },
  {
    id: "aac",
    acronym: "AAC",
    name: "African Action Congress",
    inec_registered: true,
    status: "active",
    color: "#E67E22",
  },
  {
    id: "adp",
    acronym: "ADP",
    name: "Action Democratic Party",
    inec_registered: true,
    status: "active",
    color: "#34495E",
  },
  {
    id: "apm",
    acronym: "APM",
    name: "All Allied Peoples Movement",
    inec_registered: true,
    status: "active",
    color: "#16A085",
  },
  {
    id: "app",
    acronym: "APP",
    name: "Action Peoples Party",
    inec_registered: true,
    status: "active",
    color: "#9B59B6",
  },
  {
    id: "bp",
    acronym: "BP",
    name: "Boot Party",
    inec_registered: true,
    status: "active",
    color: "#95A5A6",
  },
  {
    id: "nrm",
    acronym: "NRM",
    name: "National Rescue Movement",
    inec_registered: true,
    status: "active",
    color: "#D35400",
  },
  {
    id: "prp",
    acronym: "PRP",
    name: "People's Redemption Party",
    inec_registered: true,
    status: "active",
    color: "#C0392B",
  },
  {
    id: "zlp",
    acronym: "ZLP",
    name: "Zenith Labour Party",
    inec_registered: true,
    status: "active",
    color: "#27AE60",
  },
];

export const DEFAULT_ELECTION_CYCLE_2027: Omit<
  ElectionCycle,
  "tenant_id" | "created_by"
> = {
  id: "general-election-2027",
  name: "2027 General Elections",
  year: 2027,
  description:
    "Nigeria 2027 Presidential, Governorship, Senatorial, and Constituency Elections",
  status: "ACTIVE",
  start_date: "2027-02-20",
  end_date: "2027-03-15",
};

export const DEFAULT_CONTESTS_2027: Omit<
  ElectionContest,
  "tenant_id" | "created_by"
>[] = [
  {
    id: "2027-presidential",
    election_cycle_id: "general-election-2027",
    contest_type: "presidential",
    name: "2027 Presidential Election",
    scope_type: "national",
    scope_id: "nigeria",
    status: "OPEN",
    collation_status: "IN_PROGRESS",
    tracked_parties: ["apc", "pdp", "lp", "nnpp", "adc"],
    focus_party_id: "apc",
  },
  {
    id: "2027-enugu-governorship",
    election_cycle_id: "general-election-2027",
    contest_type: "governorship",
    name: "2027 Enugu State Governorship Election",
    scope_type: "state",
    scope_id: "enugu-state",
    state_id: "enugu-state",
    status: "OPEN",
    collation_status: "IN_PROGRESS",
    tracked_parties: ["apc", "pdp", "lp", "apga", "adc"],
    focus_party_id: "apc",
  },
  {
    id: "2027-enugu-east-senatorial",
    election_cycle_id: "general-election-2027",
    contest_type: "senatorial",
    name: "2027 Enugu East Senatorial Election",
    scope_type: "senatorial_zone",
    scope_id: "enugu-east",
    state_id: "enugu-state",
    senatorial_zone_id: "enugu-east",
    status: "OPEN",
    collation_status: "IN_PROGRESS",
    tracked_parties: ["apc", "pdp", "lp", "apga"],
    focus_party_id: "apc",
  },
  {
    id: "2027-nkanu-east-west-fed-constituency",
    election_cycle_id: "general-election-2027",
    contest_type: "federal_house",
    name: "2027 Nkanu East / Nkanu West Federal Constituency Election",
    scope_type: "federal_constituency",
    scope_id: "nkanu-east-west-fed",
    state_id: "enugu-state",
    lga_ids: ["nkanu-east", "nkanu-west"],
    status: "OPEN",
    collation_status: "IN_PROGRESS",
    tracked_parties: ["apc", "pdp", "lp", "apga"],
    focus_party_id: "apc",
  },
  {
    id: "2027-nkanu-west-state-constituency",
    election_cycle_id: "general-election-2027",
    contest_type: "state_house",
    name: "2027 Nkanu West State Constituency Election",
    scope_type: "state_constituency",
    scope_id: "nkanu-west-constituency",
    state_id: "enugu-state",
    lga_ids: ["nkanu-west"],
    status: "OPEN",
    collation_status: "IN_PROGRESS",
    tracked_parties: ["apc", "pdp", "lp", "apga"],
    focus_party_id: "apc",
  },
];
